-- ==============================================
-- NOMADXE VRM DATABASE TEMPLATE 
-- Execute this SQL inside your Supabase dashboard
-- ==============================================

-- 1. Extend auth.users with custom roles 
CREATE TABLE public.profiles (
  id uuid references auth.users not null primary key,
  role text check (role in ('admin', 'user')) default 'user'
);

-- 2. Store VRM configuration
CREATE TABLE public.victron_devices (
  id integer generated by default as identity primary key,
  vrm_site_id text not null,
  name text not null
);

-- 3. Device permission assignment matrix (Join Table)
CREATE TABLE public.device_assignments (
  id integer generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  device_id integer references public.victron_devices(id) on delete cascade not null
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.victron_devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.device_assignments ENABLE ROW LEVEL SECURITY;

-- 5. Security Policy: The Gatekeeper Rule
-- Users can strictly only see devices where their Supabase UID exists 
-- in the device_assignments table mapped by an Admin.
CREATE POLICY "Users see assigned devices" 
ON public.victron_devices
FOR SELECT
USING (
  id IN (
    SELECT device_id FROM public.device_assignments
    WHERE user_id = auth.uid()
  )
);
