-- 1. Extend auth.users with custom roles (Idempotent)
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid references auth.users not null primary key,
  role text check (role in ('admin', 'user')) default 'user',
  full_name text,
  is_active boolean default false
);

-- 2. Store VRM configuration (Idempotent)
CREATE TABLE IF NOT EXISTS public.vrm_devices (
  id integer generated by default as identity primary key,
  vrm_site_id text not null,
  name text not null
);

-- 3. Device permission assignment matrix (Join Table)
CREATE TABLE IF NOT EXISTS public.device_assignments (
  id integer generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  device_id integer references public.vrm_devices(id) on delete cascade not null
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vrm_devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.device_assignments ENABLE ROW LEVEL SECURITY;

-- 5. RLS Policies (Safe Drop & Create)

-- Profile Policy
DROP POLICY IF EXISTS "Users can view own profile" ON public.profiles;
CREATE POLICY "Users can view own profile"
  ON public.profiles FOR SELECT
  USING ( auth.uid() = id );

DROP POLICY IF EXISTS "Admins can view all profiles" ON public.profiles;
CREATE POLICY "Admins can view all profiles"
  ON public.profiles FOR SELECT
  USING ( (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin' );

-- VRM Devices RLS Policy
DROP POLICY IF EXISTS "Users see assigned devices" ON public.vrm_devices;
CREATE POLICY "Users see assigned devices" 
  ON public.vrm_devices FOR SELECT
  USING (
    id IN (
      SELECT device_id FROM public.device_assignments
      WHERE user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Admins see all devices" ON public.vrm_devices;
CREATE POLICY "Admins see all devices" 
  ON public.vrm_devices FOR SELECT
  USING ( (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin' );


-- 6. ADMIN PROMOTION
-- Replace 'admin@example.com' with your actual login email
INSERT INTO public.profiles (id, role)
SELECT id, 'admin'
FROM auth.users
WHERE email = 'admin@example.com'
ON CONFLICT (id) DO UPDATE SET role = 'admin';


-- 7. AUTO-PROFILE TRIGGER
-- Standard trigger to automatically create a profile row for new Signups
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, role, is_active)
  VALUES (
    new.id, 
    'user', 
    (CASE WHEN new.email_confirmed_at IS NOT NULL THEN true ELSE false END)
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Map the function to a trigger on the auth.users table
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
