-- ############################################################################
-- NOMADXE V2: MASTER IDENTITY MIGRATION
-- DESCRIPTION: Consolidates all tables, security, and triggers into one script.
-- RUN THIS IN SUPABASE SQL EDITOR EACH TIME YOU RESET OR SET UP THE PROJECT
-- ############################################################################

-- 1. EXTEND PROFILES (Identity Layer)
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid REFERENCES auth.users NOT NULL PRIMARY KEY,
  role TEXT CHECK (role IN ('admin', 'user')) DEFAULT 'user',
  full_name TEXT,
  status TEXT DEFAULT 'active',
  is_active BOOLEAN DEFAULT false
);

-- Add status column if it doesn't exist (for existing deployments)
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active';

-- 2. STORE DEVICES (Hardware Layer)
CREATE TABLE IF NOT EXISTS public.vrm_devices (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vrm_site_id TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL
);

-- 3. DEVICE ASSIGNMENTS (Join Table)
CREATE TABLE IF NOT EXISTS public.device_assignments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  device_id INTEGER REFERENCES public.vrm_devices(id) ON DELETE CASCADE NOT NULL,
  UNIQUE(user_id, device_id)
);

-- 4. SECURITY (Row Level Security)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vrm_devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.device_assignments ENABLE ROW LEVEL SECURITY;

-- 5. RLS POLICIES (Access Controls)
-- NOTE: Admin operations in the app use service_role (bypasses RLS entirely).
-- Only user-context read/write policies are needed here.

-- Profiles: users read/write their own row
DROP POLICY IF EXISTS "Users can view own profile" ON public.profiles;
CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Drop the recursive admin policies that caused infinite recursion
DROP POLICY IF EXISTS "Admins can view all profiles" ON public.profiles;
DROP POLICY IF EXISTS "Admins can update all profiles" ON public.profiles;

-- VRM Devices: users see only devices assigned to them
DROP POLICY IF EXISTS "Users see assigned devices" ON public.vrm_devices;
CREATE POLICY "Users see assigned devices" ON public.vrm_devices FOR SELECT
  USING (id IN (SELECT device_id FROM public.device_assignments WHERE user_id = auth.uid()));

-- Drop recursive admin device policies (service_role handles admin ops)
DROP POLICY IF EXISTS "Admins see all devices" ON public.vrm_devices;
DROP POLICY IF EXISTS "Admins manage all devices" ON public.vrm_devices;

-- Assignments: users can read their own assignments
DROP POLICY IF EXISTS "Users see own assignments" ON public.device_assignments;
CREATE POLICY "Users see own assignments" ON public.device_assignments FOR SELECT
  USING (user_id = auth.uid());

-- Drop recursive admin assignment policies (service_role handles admin ops)
DROP POLICY IF EXISTS "Admins manage all assignments" ON public.device_assignments;


-- 6. AUTO-PROFILE TRIGGER (Lifecycle)
-- Creates a profile row automatically when a new user signs up or is invited
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, role, status, is_active, full_name)
  VALUES (
    new.id,
    'user',
    'active',
    (CASE WHEN new.email_confirmed_at IS NOT NULL THEN true ELSE false END),
    (new.raw_user_meta_data->>'full_name')
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- 7. ADMIN PROMOTION
-- Sets your primary admin account. Replace the email if needed.
DO $$
DECLARE
    target_id uuid;
BEGIN
    SELECT id INTO target_id FROM auth.users WHERE lower(email) = lower('admin@nomadxe.com');

    IF target_id IS NOT NULL THEN
        INSERT INTO public.profiles (id, role, status, is_active)
        VALUES (target_id, 'admin', 'active', true)
        ON CONFLICT (id) DO UPDATE
        SET role = 'admin', status = 'active', is_active = true;
    END IF;
END $$;
