-- Managed LAN devices reported by a Cerbo GX for each VRM installation.

CREATE TABLE IF NOT EXISTS public.managed_network_devices (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vrm_device_id INTEGER NOT NULL REFERENCES public.vrm_devices(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  ip_address INET NOT NULL,
  alert_on_offline BOOLEAN NOT NULL DEFAULT true,
  is_active BOOLEAN NOT NULL DEFAULT true,
  last_status TEXT NOT NULL DEFAULT 'unknown'
    CHECK (last_status IN ('unknown', 'online', 'offline')),
  last_reported_at TIMESTAMPTZ,
  last_change_at TIMESTAMPTZ,
  last_latency_ms INTEGER CHECK (last_latency_ms IS NULL OR last_latency_ms >= 0),
  last_detail TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  UNIQUE (vrm_device_id, ip_address)
);

COMMENT ON TABLE public.managed_network_devices IS
  'Operator-managed LAN targets that a Cerbo GX checks and reports as online/offline.';

COMMENT ON COLUMN public.managed_network_devices.ip_address IS
  'Target device IP on the Cerbo LAN. Stored as inet to enforce valid addresses.';

CREATE TABLE IF NOT EXISTS public.discovered_network_devices (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vrm_device_id INTEGER NOT NULL REFERENCES public.vrm_devices(id) ON DELETE CASCADE,
  ip_address INET NOT NULL,
  mac_address TEXT,
  hostname TEXT,
  last_status TEXT NOT NULL DEFAULT 'unknown'
    CHECK (last_status IN ('unknown', 'online', 'offline')),
  first_seen_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  last_latency_ms INTEGER CHECK (last_latency_ms IS NULL OR last_latency_ms >= 0),
  last_detail TEXT,
  is_ignored BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  UNIQUE (vrm_device_id, ip_address)
);

COMMENT ON TABLE public.discovered_network_devices IS
  'LAN hosts observed by the Cerbo scan. Discovery is inventory only; alerts are driven by managed_network_devices.';

CREATE TABLE IF NOT EXISTS public.managed_network_device_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  managed_network_device_id INTEGER NOT NULL REFERENCES public.managed_network_devices(id) ON DELETE CASCADE,
  previous_status TEXT NOT NULL CHECK (previous_status IN ('unknown', 'online', 'offline')),
  next_status TEXT NOT NULL CHECK (next_status IN ('unknown', 'online', 'offline')),
  observed_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  latency_ms INTEGER CHECK (latency_ms IS NULL OR latency_ms >= 0),
  detail TEXT
);

COMMENT ON TABLE public.managed_network_device_events IS
  'Status-change audit trail for managed LAN devices reported by the Cerbo.';

CREATE INDEX IF NOT EXISTS idx_managed_network_devices_vrm_device_id
  ON public.managed_network_devices (vrm_device_id);

CREATE INDEX IF NOT EXISTS idx_managed_network_devices_last_status
  ON public.managed_network_devices (last_status);

CREATE INDEX IF NOT EXISTS idx_discovered_network_devices_vrm_device_id
  ON public.discovered_network_devices (vrm_device_id);

CREATE INDEX IF NOT EXISTS idx_discovered_network_devices_last_seen_at
  ON public.discovered_network_devices (last_seen_at DESC);

CREATE INDEX IF NOT EXISTS idx_managed_network_device_events_device_id
  ON public.managed_network_device_events (managed_network_device_id, observed_at DESC);

ALTER TABLE public.managed_network_devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.discovered_network_devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.managed_network_device_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users see assigned managed network devices" ON public.managed_network_devices;
CREATE POLICY "Users see assigned managed network devices"
  ON public.managed_network_devices
  FOR SELECT
  USING (
    vrm_device_id IN (
      SELECT vd.id
      FROM public.vrm_devices vd
      JOIN public.device_assignments da ON da.device_id = vd.id
      WHERE da.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Users see assigned discovered network devices" ON public.discovered_network_devices;
CREATE POLICY "Users see assigned discovered network devices"
  ON public.discovered_network_devices
  FOR SELECT
  USING (
    vrm_device_id IN (
      SELECT vd.id
      FROM public.vrm_devices vd
      JOIN public.device_assignments da ON da.device_id = vd.id
      WHERE da.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Users see assigned managed network events" ON public.managed_network_device_events;
CREATE POLICY "Users see assigned managed network events"
  ON public.managed_network_device_events
  FOR SELECT
  USING (
    managed_network_device_id IN (
      SELECT mnd.id
      FROM public.managed_network_devices mnd
      JOIN public.vrm_devices vd ON vd.id = mnd.vrm_device_id
      JOIN public.device_assignments da ON da.device_id = vd.id
      WHERE da.user_id = auth.uid()
    )
  );

CREATE OR REPLACE FUNCTION public.touch_managed_network_devices_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = timezone('utc', now());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_managed_network_devices_updated_at ON public.managed_network_devices;
CREATE TRIGGER trg_managed_network_devices_updated_at
  BEFORE UPDATE ON public.managed_network_devices
  FOR EACH ROW
  EXECUTE PROCEDURE public.touch_managed_network_devices_updated_at();

DROP TRIGGER IF EXISTS trg_discovered_network_devices_updated_at ON public.discovered_network_devices;
CREATE TRIGGER trg_discovered_network_devices_updated_at
  BEFORE UPDATE ON public.discovered_network_devices
  FOR EACH ROW
  EXECUTE PROCEDURE public.touch_managed_network_devices_updated_at();
