-- ############################################################################
-- MIGRATION 009: Atomic token rotation RPC + email→user_id lookup
--
-- Fixes two race conditions identified in security audit:
--
--   1. rotate_auth_token — Replaces the separate UPDATE+INSERT pattern in
--      createAuthToken with a single PL/pgSQL function that runs both
--      statements inside one implicit transaction. Eliminates the TOCTOU
--      window where a second concurrent call could insert a duplicate token
--      before the first's invalidation is visible.
--
--   2. get_user_id_by_email — Replaces adminClient.auth.admin.listUsers()
--      O(n) full-table scan on every public password reset request with a
--      targeted query against auth.users. Function is SECURITY DEFINER so
--      the caller doesn't need direct access to auth schema.
--
-- Run in: Supabase Dashboard → SQL Editor → New Query
-- ############################################################################

-- ── 1. Atomic token rotation ──────────────────────────────────────────────────
-- Parameters:
--   p_user_id    — UUID of the user
--   p_type       — 'invite' or 'recovery'
--   p_token      — New hex token string (64 chars, generated by crypto)
--   p_expires_at — Timestamp when the new token expires
--
-- Effect:
--   a) Marks ALL prior unused tokens of (user_id, type) as used (expires them)
--   b) Inserts the new token
--   Both in a single PL/pgSQL block → single implicit transaction.

CREATE OR REPLACE FUNCTION public.rotate_auth_token(
  p_user_id    uuid,
  p_type       text,
  p_token      text,
  p_expires_at timestamptz
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Invalidate all prior unused tokens of same type for this user
  UPDATE public.auth_tokens
  SET    used_at = now()
  WHERE  user_id  = p_user_id
    AND  type     = p_type
    AND  used_at IS NULL;

  -- Insert the new token
  INSERT INTO public.auth_tokens (token, user_id, type, expires_at)
  VALUES (p_token, p_user_id, p_type, p_expires_at);
END;
$$;

-- Restrict direct invocation to service_role only
REVOKE EXECUTE ON FUNCTION public.rotate_auth_token(uuid, text, text, timestamptz)
  FROM PUBLIC, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.rotate_auth_token(uuid, text, text, timestamptz)
  TO service_role;


-- ── 2. Email → user ID lookup ─────────────────────────────────────────────────
-- Used by requestPasswordReset server action to replace the O(n) listUsers()
-- call with a targeted query. Returns NULL if no user exists for that email
-- (allows the caller to proceed without revealing whether the user exists).

CREATE OR REPLACE FUNCTION public.get_user_id_by_email(email_input text)
RETURNS uuid
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT id
  FROM   auth.users
  WHERE  lower(email) = lower(email_input)
  LIMIT  1;
$$;

-- Restrict to service_role — should never be callable by authenticated users
-- (would allow email enumeration).
REVOKE EXECUTE ON FUNCTION public.get_user_id_by_email(text)
  FROM PUBLIC, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.get_user_id_by_email(text)
  TO service_role;
