-- Cellular signal readings reported from Teltonika/Cerbo/RMS collection.
-- Customers can read assigned-device reports; writes remain server/ingest only.

CREATE TABLE IF NOT EXISTS public.cellular_signal_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vrm_device_id INTEGER NOT NULL REFERENCES public.vrm_devices(id) ON DELETE CASCADE,
  observed_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  source TEXT NOT NULL DEFAULT 'cerbo'
    CHECK (source IN ('cerbo', 'teltonika_rms', 'router_api', 'manual')),
  operator TEXT,
  network_type TEXT,
  band TEXT,
  rssi_dbm INTEGER,
  rsrp_dbm INTEGER,
  rsrq_db NUMERIC(6,2),
  sinr_db NUMERIC(6,2),
  connection_state TEXT,
  detail TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

CREATE INDEX IF NOT EXISTS idx_cellular_signal_reports_device_time
  ON public.cellular_signal_reports (vrm_device_id, observed_at DESC);

ALTER TABLE public.cellular_signal_reports ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users see assigned cellular signal reports" ON public.cellular_signal_reports;
CREATE POLICY "Users see assigned cellular signal reports"
  ON public.cellular_signal_reports
  FOR SELECT
  USING (public.user_can_access_vrm_device(vrm_device_id));

REVOKE INSERT, UPDATE, DELETE ON public.cellular_signal_reports FROM anon, authenticated;
GRANT SELECT ON public.cellular_signal_reports TO authenticated;
