-- ############################################################################
-- NOMADXE V2: MASTER IDENTITY MIGRATION
-- DESCRIPTION: Consolidates all tables, security, and triggers into one script.
-- ############################################################################

-- 1. EXTEND PROFILES (Identity Layer)
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid REFERENCES auth.users NOT NULL PRIMARY KEY,
  role TEXT CHECK (role IN ('admin', 'user')) DEFAULT 'user',
  full_name TEXT,
  is_active BOOLEAN DEFAULT false
);

-- 2. STORE DEVICES (Hardware Layer)
CREATE TABLE IF NOT EXISTS public.vrm_devices (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vrm_site_id TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL
);

-- 3. DEVICE ASSIGNMENTS (Join Table)
CREATE TABLE IF NOT EXISTS public.device_assignments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  device_id INTEGER REFERENCES public.vrm_devices(id) ON DELETE CASCADE NOT NULL,
  UNIQUE(user_id, device_id)
);

-- 4. SECURITY (Row Level Security)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vrm_devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.device_assignments ENABLE ROW LEVEL SECURITY;

-- 5. RLS POLICIES (Access Controls)

-- Profiles
DROP POLICY IF EXISTS "Users can view own profile" ON public.profiles;
CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS "Admins can view all profiles" ON public.profiles;
CREATE POLICY "Admins can view all profiles" ON public.profiles FOR SELECT USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin');

DROP POLICY IF EXISTS "Admins can update all profiles" ON public.profiles;
CREATE POLICY "Admins can update all profiles" ON public.profiles FOR UPDATE USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin');

-- VRM Devices
DROP POLICY IF EXISTS "Users see assigned devices" ON public.vrm_devices;
CREATE POLICY "Users see assigned devices" ON public.vrm_devices FOR SELECT USING (id IN (SELECT device_id FROM public.device_assignments WHERE user_id = auth.uid()));

DROP POLICY IF EXISTS "Admins see all devices" ON public.vrm_devices;
CREATE POLICY "Admins see all devices" ON public.vrm_devices FOR SELECT USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin');

DROP POLICY IF EXISTS "Admins manage all devices" ON public.vrm_devices;
CREATE POLICY "Admins manage all devices" ON public.vrm_devices FOR ALL USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin');

-- Assignments
DROP POLICY IF EXISTS "Admins manage all assignments" ON public.device_assignments;
CREATE POLICY "Admins manage all assignments" ON public.device_assignments FOR ALL USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin');


-- 6. AUTO-PROFILE TRIGGER (Lifecycle)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, role, is_active, full_name)
  VALUES (
    new.id, 
    'user', 
    (CASE WHEN new.email_confirmed_at IS NOT NULL THEN true ELSE false END),
    (new.raw_user_meta_data->>'full_name')
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- 7. 🚨 ADMIN PROMOTION (Identity Hook)
-- Replace the email below with your definitive admin account
DO $$
DECLARE
    target_id uuid;
BEGIN
    SELECT id INTO target_id FROM auth.users WHERE lower(email) = lower('admin@nomadxe.com'); -- 🗺️ SET EMAIL HERE
    
    IF target_id IS NOT NULL THEN
        INSERT INTO public.profiles (id, role, is_active)
        VALUES (target_id, 'admin', true)
        ON CONFLICT (id) DO UPDATE 
        SET role = 'admin', is_active = true;
    END IF;
END $$;
